version: "3"
services:
  app:
    build: .
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hudson
    volumes:
      - ./pgdata:/var/lib/postgresql/data